/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeoReportInfographicRouteImport } from './routes/seo-report-infographic'
import { Route as SeoInfographicsRouteImport } from './routes/seo-infographics'
import { Route as SeoInfographicExamplesRouteImport } from './routes/seo-infographic-examples'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GscInfographicReportRouteImport } from './routes/gsc-infographic-report'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoReportInfographicRoute = SeoReportInfographicRouteImport.update({
  id: '/seo-report-infographic',
  path: '/seo-report-infographic',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoInfographicsRoute = SeoInfographicsRouteImport.update({
  id: '/seo-infographics',
  path: '/seo-infographics',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoInfographicExamplesRoute = SeoInfographicExamplesRouteImport.update({
  id: '/seo-infographic-examples',
  path: '/seo-infographic-examples',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GscInfographicReportRoute = GscInfographicReportRouteImport.update({
  id: '/gsc-infographic-report',
  path: '/gsc-infographic-report',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gsc-infographic-report': typeof GscInfographicReportRoute
  '/pricing': typeof PricingRoute
  '/seo-infographic-examples': typeof SeoInfographicExamplesRoute
  '/seo-infographics': typeof SeoInfographicsRoute
  '/seo-report-infographic': typeof SeoReportInfographicRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gsc-infographic-report': typeof GscInfographicReportRoute
  '/pricing': typeof PricingRoute
  '/seo-infographic-examples': typeof SeoInfographicExamplesRoute
  '/seo-infographics': typeof SeoInfographicsRoute
  '/seo-report-infographic': typeof SeoReportInfographicRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gsc-infographic-report': typeof GscInfographicReportRoute
  '/pricing': typeof PricingRoute
  '/seo-infographic-examples': typeof SeoInfographicExamplesRoute
  '/seo-infographics': typeof SeoInfographicsRoute
  '/seo-report-infographic': typeof SeoReportInfographicRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/gsc-infographic-report'
    | '/pricing'
    | '/seo-infographic-examples'
    | '/seo-infographics'
    | '/seo-report-infographic'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/gsc-infographic-report'
    | '/pricing'
    | '/seo-infographic-examples'
    | '/seo-infographics'
    | '/seo-report-infographic'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/gsc-infographic-report'
    | '/pricing'
    | '/seo-infographic-examples'
    | '/seo-infographics'
    | '/seo-report-infographic'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GscInfographicReportRoute: typeof GscInfographicReportRoute
  PricingRoute: typeof PricingRoute
  SeoInfographicExamplesRoute: typeof SeoInfographicExamplesRoute
  SeoInfographicsRoute: typeof SeoInfographicsRoute
  SeoReportInfographicRoute: typeof SeoReportInfographicRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-report-infographic': {
      id: '/seo-report-infographic'
      path: '/seo-report-infographic'
      fullPath: '/seo-report-infographic'
      preLoaderRoute: typeof SeoReportInfographicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-infographics': {
      id: '/seo-infographics'
      path: '/seo-infographics'
      fullPath: '/seo-infographics'
      preLoaderRoute: typeof SeoInfographicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-infographic-examples': {
      id: '/seo-infographic-examples'
      path: '/seo-infographic-examples'
      fullPath: '/seo-infographic-examples'
      preLoaderRoute: typeof SeoInfographicExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gsc-infographic-report': {
      id: '/gsc-infographic-report'
      path: '/gsc-infographic-report'
      fullPath: '/gsc-infographic-report'
      preLoaderRoute: typeof GscInfographicReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GscInfographicReportRoute: GscInfographicReportRoute,
  PricingRoute: PricingRoute,
  SeoInfographicExamplesRoute: SeoInfographicExamplesRoute,
  SeoInfographicsRoute: SeoInfographicsRoute,
  SeoReportInfographicRoute: SeoReportInfographicRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
